### ISSUE TITLE
ImportError: cannot import name 'sRGB_to_XYZ' from 'colour'

### ISSUE THREAD

**Issue by elindgren** [m-ulmestrand/perfect-cmaps#1]
Imports of some functions like `sRGB_to_XYZ` does not seem to work anymore. From what I can tell, they are not available in the [colour](https://github.com/vaab/colour) package anymore. The package also seems abandoned. Should there perhaps be a cap on which version of `colour` to use in the `requirements.txt`-file?

**Comment by m-ulmestrand** [comment]
Sorry about that -- wrong package actually. There's a package called `colour`, but the correct one is actually `colour-science`, which imports as `colour`. Fixed that in commit `b161e99`. Hope it works now!
