### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'

### ISSUE THREAD

**Issue by elindgren** [m-ulmestrand/perfect-cmaps#2]
`colour-science` allowed me to get to the next imports in colormaps, and here I get an error due to `cv2` not being installed. There does not seem to be a candidate for it on pypi; perhaps it's part of some other package?

**Comment by m-ulmestrand** [comment]
Ah, clearly this requirements file isn't healthy. That's OpenCV. I'm using `opencv-python-headless` to not conflict with `matplotlib`. Adding that to the requirements file in commit `b30a09f`.

**Comment by m-ulmestrand** [comment]
Noticed that `numba` was missing from requirements as well, let me know if there's anything else and I'll rectify it!

**Comment by elindgren** [comment]
It works now, thanks!
